name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -e .
        pip install pdoc

    - name: Build documentation with pdoc
      run: |
        pdoc --footer-text "© 2025 IFRI Machine Learning Library" -o docs/ ifri_mini_ml_lib
        touch docs/.nojekyll

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
